---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-bigip-ipam
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-bigip-ipam
rules:
- apiGroups: [""]
  resources:
  - services
  verbs:
  - list
  - get
  - update
  - patch
  - watch
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - ipam.nexinto.com
  resources:
  - ipaddresses
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-bigip-ipam
subjects:
- kind: ServiceAccount
  name: k8s-bigip-ipam
  namespace: kube-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: k8s-bigip-ipam
